export const REBALANCING_PROVIDE = Object.freeze({
  MAIN: 'MainRebalancing',
});

export const ENGINE_TOKENS_SUPPORTED = Object.freeze({
  WAIV: 'WAIV',
  SWAP_BTC: 'SWAP.BTC',
  SWAP_HBD: 'SWAP.HBD',
  SWAP_HIVE: 'SWAP.HIVE',
  SWAP_ETH: 'SWAP.ETH',
  SWAP_LTC: 'SWAP.LTC',
});

export const ENGINE_TOKENS_FOR_PRECISION = [
  ...Object.values(ENGINE_TOKENS_SUPPORTED),
];

export const REBALANCING_POOLS = [
  `${ENGINE_TOKENS_SUPPORTED.SWAP_HIVE}:${ENGINE_TOKENS_SUPPORTED.WAIV}`,
  `${ENGINE_TOKENS_SUPPORTED.SWAP_HIVE}:${ENGINE_TOKENS_SUPPORTED.SWAP_BTC}`,
  `${ENGINE_TOKENS_SUPPORTED.SWAP_HIVE}:${ENGINE_TOKENS_SUPPORTED.SWAP_HBD}`,
  `${ENGINE_TOKENS_SUPPORTED.SWAP_HIVE}:${ENGINE_TOKENS_SUPPORTED.SWAP_ETH}`,
  `${ENGINE_TOKENS_SUPPORTED.SWAP_HIVE}:${ENGINE_TOKENS_SUPPORTED.SWAP_LTC}`,
  `${ENGINE_TOKENS_SUPPORTED.SWAP_BTC}:${ENGINE_TOKENS_SUPPORTED.SWAP_ETH}`,
];

export const REBALANCE_PAIRS_WAIV = [
  {
    base: ENGINE_TOKENS_SUPPORTED.WAIV,
    quote: ENGINE_TOKENS_SUPPORTED.SWAP_BTC,
    directPool: false,
    basePool: `${ENGINE_TOKENS_SUPPORTED.SWAP_HIVE}:${ENGINE_TOKENS_SUPPORTED.WAIV}`,
    quotePool: `${ENGINE_TOKENS_SUPPORTED.SWAP_HIVE}:${ENGINE_TOKENS_SUPPORTED.SWAP_BTC}`,
  },
  {
    base: ENGINE_TOKENS_SUPPORTED.WAIV,
    quote: ENGINE_TOKENS_SUPPORTED.SWAP_HBD,
    directPool: false,
    basePool: `${ENGINE_TOKENS_SUPPORTED.SWAP_HIVE}:${ENGINE_TOKENS_SUPPORTED.WAIV}`,
    quotePool: `${ENGINE_TOKENS_SUPPORTED.SWAP_HIVE}:${ENGINE_TOKENS_SUPPORTED.SWAP_HBD}`,
  },
  {
    base: ENGINE_TOKENS_SUPPORTED.WAIV,
    quote: ENGINE_TOKENS_SUPPORTED.SWAP_ETH,
    directPool: false,
    basePool: `${ENGINE_TOKENS_SUPPORTED.SWAP_HIVE}:${ENGINE_TOKENS_SUPPORTED.WAIV}`,
    quotePool: `${ENGINE_TOKENS_SUPPORTED.SWAP_HIVE}:${ENGINE_TOKENS_SUPPORTED.SWAP_ETH}`,
  },
  {
    base: ENGINE_TOKENS_SUPPORTED.WAIV,
    quote: ENGINE_TOKENS_SUPPORTED.SWAP_LTC,
    directPool: false,
    basePool: `${ENGINE_TOKENS_SUPPORTED.SWAP_HIVE}:${ENGINE_TOKENS_SUPPORTED.WAIV}`,
    quotePool: `${ENGINE_TOKENS_SUPPORTED.SWAP_HIVE}:${ENGINE_TOKENS_SUPPORTED.SWAP_LTC}`,
  },
];

export const REBALANCE_PAIRS_HIVE = [
  {
    base: ENGINE_TOKENS_SUPPORTED.SWAP_HIVE,
    quote: ENGINE_TOKENS_SUPPORTED.SWAP_HBD,
    directPool: true,
    pool: `${ENGINE_TOKENS_SUPPORTED.SWAP_HIVE}:${ENGINE_TOKENS_SUPPORTED.SWAP_HBD}`,
  },
  {
    base: ENGINE_TOKENS_SUPPORTED.SWAP_HIVE,
    quote: ENGINE_TOKENS_SUPPORTED.SWAP_BTC,
    directPool: true,
    pool: `${ENGINE_TOKENS_SUPPORTED.SWAP_HIVE}:${ENGINE_TOKENS_SUPPORTED.SWAP_BTC}`,
  },
  {
    base: ENGINE_TOKENS_SUPPORTED.SWAP_HIVE,
    quote: ENGINE_TOKENS_SUPPORTED.SWAP_ETH,
    directPool: true,
    pool: `${ENGINE_TOKENS_SUPPORTED.SWAP_HIVE}:${ENGINE_TOKENS_SUPPORTED.SWAP_ETH}`,
  },
];

export const REBALANCE_PAIRS_BTC = [
  {
    base: ENGINE_TOKENS_SUPPORTED.SWAP_BTC,
    quote: ENGINE_TOKENS_SUPPORTED.SWAP_ETH,
    directPool: true,
    pool: `${ENGINE_TOKENS_SUPPORTED.SWAP_BTC}:${ENGINE_TOKENS_SUPPORTED.SWAP_ETH}`,
  },
  {
    base: ENGINE_TOKENS_SUPPORTED.SWAP_BTC,
    quote: ENGINE_TOKENS_SUPPORTED.SWAP_HBD,
    directPool: false,
    basePool: `${ENGINE_TOKENS_SUPPORTED.SWAP_HIVE}:${ENGINE_TOKENS_SUPPORTED.SWAP_BTC}`,
    quotePool: `${ENGINE_TOKENS_SUPPORTED.SWAP_HIVE}:${ENGINE_TOKENS_SUPPORTED.SWAP_HBD}`,
  },
];

export const REBALANCE_PAIRS_ETH = [
  {
    base: ENGINE_TOKENS_SUPPORTED.SWAP_ETH,
    quote: ENGINE_TOKENS_SUPPORTED.SWAP_HBD,
    directPool: false,
    basePool: `${ENGINE_TOKENS_SUPPORTED.SWAP_HIVE}:${ENGINE_TOKENS_SUPPORTED.SWAP_ETH}`,
    quotePool: `${ENGINE_TOKENS_SUPPORTED.SWAP_HIVE}:${ENGINE_TOKENS_SUPPORTED.SWAP_HBD}`,
  },
];
