export const REBALANCING_PROVIDE = Object.freeze({
  MAIN: 'MainRebalancing',
});

export const ENGINE_TOKENS_SUPPORTED = Object.freeze({
  WAIV: 'WAIV',
  SPS: 'SPS',
  DEC: 'DEC',
  SWAP_BTC: 'SWAP.BTC',
  SWAP_HBD: 'SWAP.HBD',
  SWAP_HIVE: 'SWAP.HIVE',
  SWAP_ETH: 'SWAP.ETH',
  SWAP_LTC: 'SWAP.LTC',
});

export const TOKENS_PRECISION = Object.freeze({
  DEC: 3,
});

export const DB_REBALANCING_FIELD = Object.freeze({
  WAIV_BTC: 'WAIV_BTC',
  WAIV_HBD: 'WAIV_HBD',
  WAIV_ETH: 'WAIV_ETH',
  WAIV_LTC: 'WAIV_LTC',
  HIVE_HBD: 'HIVE_HBD',
  HIVE_BTC: 'HIVE_BTC',
  HIVE_ETH: 'HIVE_ETH',
  HIVE_LTC: 'HIVE_LTC',
  BTC_ETH: 'BTC_ETH',
  BTC_HBD: 'BTC_HBD',
  ETH_HBD: 'ETH_HBD',
  SPS_HIVE: 'SPS_HIVE',
  SPS_ETH: 'SPS_ETH',
  SPS_BTC: 'SPS_BTC',
  SPS_LTC: 'SPS_LTC',
  DEC_HIVE: 'DEC_HIVE',
  DEC_ETH: 'DEC_ETH',
  DEC_BTC: 'DEC_BTC',
  DEC_LTC: 'DEC_LTC',
});

export const REBALANCING_POOLS = [
  `${ENGINE_TOKENS_SUPPORTED.SWAP_HIVE}:${ENGINE_TOKENS_SUPPORTED.WAIV}`,
  `${ENGINE_TOKENS_SUPPORTED.SWAP_HIVE}:${ENGINE_TOKENS_SUPPORTED.SWAP_BTC}`,
  `${ENGINE_TOKENS_SUPPORTED.SWAP_HIVE}:${ENGINE_TOKENS_SUPPORTED.SWAP_HBD}`,
  `${ENGINE_TOKENS_SUPPORTED.SWAP_HIVE}:${ENGINE_TOKENS_SUPPORTED.SWAP_ETH}`,
  `${ENGINE_TOKENS_SUPPORTED.SWAP_HIVE}:${ENGINE_TOKENS_SUPPORTED.SWAP_LTC}`,
  `${ENGINE_TOKENS_SUPPORTED.SWAP_BTC}:${ENGINE_TOKENS_SUPPORTED.SWAP_ETH}`,
  `${ENGINE_TOKENS_SUPPORTED.SWAP_HIVE}:${ENGINE_TOKENS_SUPPORTED.SPS}`,
  `${ENGINE_TOKENS_SUPPORTED.SWAP_ETH}:${ENGINE_TOKENS_SUPPORTED.SPS}`,
  `${ENGINE_TOKENS_SUPPORTED.SWAP_BTC}:${ENGINE_TOKENS_SUPPORTED.SPS}`,
  `${ENGINE_TOKENS_SUPPORTED.SWAP_HIVE}:${ENGINE_TOKENS_SUPPORTED.DEC}`,
];

export const REBALANCE_PAIRS_WAIV = [
  {
    base: ENGINE_TOKENS_SUPPORTED.WAIV,
    quote: ENGINE_TOKENS_SUPPORTED.SWAP_BTC,
    directPool: false,
    basePool: `${ENGINE_TOKENS_SUPPORTED.SWAP_HIVE}:${ENGINE_TOKENS_SUPPORTED.WAIV}`,
    quotePool: `${ENGINE_TOKENS_SUPPORTED.SWAP_HIVE}:${ENGINE_TOKENS_SUPPORTED.SWAP_BTC}`,
    dbField: DB_REBALANCING_FIELD.WAIV_BTC,
  },
  {
    base: ENGINE_TOKENS_SUPPORTED.WAIV,
    quote: ENGINE_TOKENS_SUPPORTED.SWAP_HBD,
    directPool: false,
    basePool: `${ENGINE_TOKENS_SUPPORTED.SWAP_HIVE}:${ENGINE_TOKENS_SUPPORTED.WAIV}`,
    quotePool: `${ENGINE_TOKENS_SUPPORTED.SWAP_HIVE}:${ENGINE_TOKENS_SUPPORTED.SWAP_HBD}`,
    dbField: DB_REBALANCING_FIELD.WAIV_HBD,
  },
  {
    base: ENGINE_TOKENS_SUPPORTED.WAIV,
    quote: ENGINE_TOKENS_SUPPORTED.SWAP_ETH,
    directPool: false,
    basePool: `${ENGINE_TOKENS_SUPPORTED.SWAP_HIVE}:${ENGINE_TOKENS_SUPPORTED.WAIV}`,
    quotePool: `${ENGINE_TOKENS_SUPPORTED.SWAP_HIVE}:${ENGINE_TOKENS_SUPPORTED.SWAP_ETH}`,
    dbField: DB_REBALANCING_FIELD.WAIV_ETH,
  },
  {
    base: ENGINE_TOKENS_SUPPORTED.WAIV,
    quote: ENGINE_TOKENS_SUPPORTED.SWAP_LTC,
    directPool: false,
    basePool: `${ENGINE_TOKENS_SUPPORTED.SWAP_HIVE}:${ENGINE_TOKENS_SUPPORTED.WAIV}`,
    quotePool: `${ENGINE_TOKENS_SUPPORTED.SWAP_HIVE}:${ENGINE_TOKENS_SUPPORTED.SWAP_LTC}`,
    dbField: DB_REBALANCING_FIELD.WAIV_LTC,
  },
];

export const REBALANCE_PAIRS_HIVE = [
  {
    base: ENGINE_TOKENS_SUPPORTED.SWAP_HIVE,
    quote: ENGINE_TOKENS_SUPPORTED.SWAP_HBD,
    directPool: true,
    pool: `${ENGINE_TOKENS_SUPPORTED.SWAP_HIVE}:${ENGINE_TOKENS_SUPPORTED.SWAP_HBD}`,
    dbField: DB_REBALANCING_FIELD.HIVE_HBD,
  },
  {
    base: ENGINE_TOKENS_SUPPORTED.SWAP_HIVE,
    quote: ENGINE_TOKENS_SUPPORTED.SWAP_BTC,
    directPool: true,
    pool: `${ENGINE_TOKENS_SUPPORTED.SWAP_HIVE}:${ENGINE_TOKENS_SUPPORTED.SWAP_BTC}`,
    dbField: DB_REBALANCING_FIELD.HIVE_BTC,
  },
  {
    base: ENGINE_TOKENS_SUPPORTED.SWAP_HIVE,
    quote: ENGINE_TOKENS_SUPPORTED.SWAP_ETH,
    directPool: true,
    pool: `${ENGINE_TOKENS_SUPPORTED.SWAP_HIVE}:${ENGINE_TOKENS_SUPPORTED.SWAP_ETH}`,
    dbField: DB_REBALANCING_FIELD.HIVE_ETH,
  },
  {
    base: ENGINE_TOKENS_SUPPORTED.SWAP_HIVE,
    quote: ENGINE_TOKENS_SUPPORTED.SWAP_LTC,
    directPool: true,
    pool: `${ENGINE_TOKENS_SUPPORTED.SWAP_HIVE}:${ENGINE_TOKENS_SUPPORTED.SWAP_LTC}`,
    dbField: DB_REBALANCING_FIELD.HIVE_LTC,
  },
];

export const REBALANCE_PAIRS_BTC = [
  {
    base: ENGINE_TOKENS_SUPPORTED.SWAP_BTC,
    quote: ENGINE_TOKENS_SUPPORTED.SWAP_ETH,
    directPool: true,
    pool: `${ENGINE_TOKENS_SUPPORTED.SWAP_BTC}:${ENGINE_TOKENS_SUPPORTED.SWAP_ETH}`,
    dbField: DB_REBALANCING_FIELD.BTC_ETH,
  },
  {
    base: ENGINE_TOKENS_SUPPORTED.SWAP_BTC,
    quote: ENGINE_TOKENS_SUPPORTED.SWAP_HBD,
    directPool: false,
    basePool: `${ENGINE_TOKENS_SUPPORTED.SWAP_HIVE}:${ENGINE_TOKENS_SUPPORTED.SWAP_BTC}`,
    quotePool: `${ENGINE_TOKENS_SUPPORTED.SWAP_HIVE}:${ENGINE_TOKENS_SUPPORTED.SWAP_HBD}`,
    dbField: DB_REBALANCING_FIELD.BTC_HBD,
  },
];

export const REBALANCE_PAIRS_ETH = [
  {
    base: ENGINE_TOKENS_SUPPORTED.SWAP_ETH,
    quote: ENGINE_TOKENS_SUPPORTED.SWAP_HBD,
    directPool: false,
    basePool: `${ENGINE_TOKENS_SUPPORTED.SWAP_HIVE}:${ENGINE_TOKENS_SUPPORTED.SWAP_ETH}`,
    quotePool: `${ENGINE_TOKENS_SUPPORTED.SWAP_HIVE}:${ENGINE_TOKENS_SUPPORTED.SWAP_HBD}`,
    dbField: DB_REBALANCING_FIELD.ETH_HBD,
  },
];

export const REBALANCE_PAIRS_SPS = [
  {
    base: ENGINE_TOKENS_SUPPORTED.SPS,
    quote: ENGINE_TOKENS_SUPPORTED.SWAP_HIVE,
    directPool: true,
    pool: `${ENGINE_TOKENS_SUPPORTED.SWAP_HIVE}:${ENGINE_TOKENS_SUPPORTED.SPS}`,
    dbField: DB_REBALANCING_FIELD.SPS_HIVE,
  },
  {
    base: ENGINE_TOKENS_SUPPORTED.SPS,
    quote: ENGINE_TOKENS_SUPPORTED.SWAP_ETH,
    directPool: true,
    pool: `${ENGINE_TOKENS_SUPPORTED.SWAP_ETH}:${ENGINE_TOKENS_SUPPORTED.SPS}`,
    dbField: DB_REBALANCING_FIELD.SPS_ETH,
  },
  {
    base: ENGINE_TOKENS_SUPPORTED.SPS,
    quote: ENGINE_TOKENS_SUPPORTED.SWAP_BTC,
    directPool: true,
    pool: `${ENGINE_TOKENS_SUPPORTED.SWAP_BTC}:${ENGINE_TOKENS_SUPPORTED.SPS}`,
    dbField: DB_REBALANCING_FIELD.SPS_BTC,
  },
  {
    base: ENGINE_TOKENS_SUPPORTED.SPS,
    quote: ENGINE_TOKENS_SUPPORTED.SWAP_LTC,
    directPool: false,
    basePool: `${ENGINE_TOKENS_SUPPORTED.SWAP_HIVE}:${ENGINE_TOKENS_SUPPORTED.SPS}`,
    quotePool: `${ENGINE_TOKENS_SUPPORTED.SWAP_HIVE}:${ENGINE_TOKENS_SUPPORTED.SWAP_LTC}`,
    dbField: DB_REBALANCING_FIELD.SPS_LTC,
  },
];

export const REBALANCE_PAIRS_DEC = [
  {
    base: ENGINE_TOKENS_SUPPORTED.DEC,
    quote: ENGINE_TOKENS_SUPPORTED.SWAP_HIVE,
    directPool: true,
    pool: `${ENGINE_TOKENS_SUPPORTED.SWAP_HIVE}:${ENGINE_TOKENS_SUPPORTED.DEC}`,
    dbField: DB_REBALANCING_FIELD.DEC_HIVE,
  },
  {
    base: ENGINE_TOKENS_SUPPORTED.DEC,
    quote: ENGINE_TOKENS_SUPPORTED.SWAP_ETH,
    directPool: false,
    basePool: `${ENGINE_TOKENS_SUPPORTED.SWAP_HIVE}:${ENGINE_TOKENS_SUPPORTED.DEC}`,
    quotePool: `${ENGINE_TOKENS_SUPPORTED.SWAP_HIVE}:${ENGINE_TOKENS_SUPPORTED.SWAP_ETH}`,
    dbField: DB_REBALANCING_FIELD.DEC_ETH,
  },
  {
    base: ENGINE_TOKENS_SUPPORTED.DEC,
    quote: ENGINE_TOKENS_SUPPORTED.SWAP_BTC,
    directPool: false,
    basePool: `${ENGINE_TOKENS_SUPPORTED.SWAP_HIVE}:${ENGINE_TOKENS_SUPPORTED.DEC}`,
    quotePool: `${ENGINE_TOKENS_SUPPORTED.SWAP_HIVE}:${ENGINE_TOKENS_SUPPORTED.SWAP_BTC}`,
    dbField: DB_REBALANCING_FIELD.DEC_BTC,
  },
  {
    base: ENGINE_TOKENS_SUPPORTED.DEC,
    quote: ENGINE_TOKENS_SUPPORTED.SWAP_LTC,
    directPool: false,
    basePool: `${ENGINE_TOKENS_SUPPORTED.SWAP_HIVE}:${ENGINE_TOKENS_SUPPORTED.DEC}`,
    quotePool: `${ENGINE_TOKENS_SUPPORTED.SWAP_HIVE}:${ENGINE_TOKENS_SUPPORTED.SWAP_LTC}`,
    dbField: DB_REBALANCING_FIELD.DEC_LTC,
  },
];

export const DEFAULT_SLIPPAGE = 0.0001;
export const DEFAULT_SLIPPAGE_MAX = 0.01;
export const DEFAULT_PRECISION = 8;
export const DEFAULT_TRADE_FEE_MUL = 0.9975;
